import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/app/ui/footer";
import Header from "@/app/ui/header";
import { Toaster } from "react-hot-toast";



export const metadata: Metadata = {
  title: "Poké System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body>
        <Header />
        {children}
        <Footer />
        <Toaster position="top-right"/>
      </body>
    </html>
  );
}
