import type { Metadata } from "next";

import {Montserrat} from 'next/font/google';

import  "@/app/globals.css";
import Header from "./ui/header";
import Footer from "./ui/footer";

const montserrat = Montserrat({ subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
